import type { HeroSlideRow } from "@/lib/content";

/** 26 banner slides — one for each primary artwork plate. */
export const HERO_SLIDES: HeroSlideRow[] = [
  {
    id: "hero-01",
    subject_slug: "biology",
    title: "The living cell",
    subtitle: "Nucleus, membranes and the chemistry of being alive",
    body: "Start inside a eukaryotic cell — organelles glowing like a city at night.",
    image_key: "hero-cell",
    image_url: null,
    link_to: "/cells-microscopy",
    video_url: null,
    sort: 0,
    active: true,
  },
  {
    id: "hero-02",
    subject_slug: "biology",
    title: "Kingdoms of life",
    subtitle: "Animals, fungi, protists, bacteria, archaea",
    body: "A survey of body plans and how taxonomists draw the tree.",
    image_key: "cat-organisms",
    image_url: null,
    link_to: "/organisms",
    video_url: null,
    sort: 1,
    active: true,
  },
  {
    id: "hero-03",
    subject_slug: "biology",
    title: "The double helix",
    subtitle: "Genes, replication and inheritance",
    body: "From base pairing to Mendel — how information becomes a trait.",
    image_key: "cat-genetics",
    image_url: null,
    link_to: "/genetics-dna",
    video_url: null,
    sort: 2,
    active: true,
  },
  {
    id: "hero-04",
    subject_slug: "biology",
    title: "The human body",
    subtitle: "Systems in motion",
    body: "Heart, lung, nerve and gut as one cooperating machine.",
    image_key: "cat-human",
    image_url: null,
    link_to: "/human-biology",
    video_url: null,
    sort: 3,
    active: true,
  },
  {
    id: "hero-05",
    subject_slug: "biology",
    title: "Green engines",
    subtitle: "Leaves, light and sugars",
    body: "Photosynthesis feeds nearly every food web on Earth.",
    image_key: "cat-plants",
    image_url: null,
    link_to: "/plants",
    video_url: null,
    sort: 4,
    active: true,
  },
  {
    id: "hero-06",
    subject_slug: "biology",
    title: "Webs of energy",
    subtitle: "Ecology at twilight",
    body: "Follow carbon, nitrogen and trophic levels through a living landscape.",
    image_key: "cat-ecology",
    image_url: null,
    link_to: "/ecology-environment",
    video_url: null,
    sort: 5,
    active: true,
  },
  {
    id: "hero-07",
    subject_slug: "biology",
    title: "Deep time",
    subtitle: "Selection, fossils and new species",
    body: "Four billion years of change, written in rock and DNA.",
    image_key: "cat-evolution",
    image_url: null,
    link_to: "/evolution",
    video_url: null,
    sort: 6,
    active: true,
  },
  {
    id: "hero-08",
    subject_slug: "biology",
    title: "Discover",
    subtitle: "A leaf as a laboratory",
    body: "Every article begins with looking closely. Open the encyclopedia.",
    image_key: "discovery-leaf",
    image_url: null,
    link_to: "/articles",
    video_url: null,
    sort: 7,
    active: true,
  },
  {
    id: "hero-09",
    subject_slug: "mathematics",
    title: "The unknown quantity",
    subtitle: "Algebra as a language",
    body: "Equations, functions and the art of naming what you do not yet know.",
    image_key: "math-algebra",
    image_url: null,
    link_to: "/mathematics/algebra",
    video_url: null,
    sort: 8,
    active: true,
  },
  {
    id: "hero-10",
    subject_slug: "mathematics",
    title: "Shape and proof",
    subtitle: "Geometry's quiet light",
    body: "Axioms, diagrams and the logic that holds space together.",
    image_key: "math-geometry",
    image_url: null,
    link_to: "/mathematics/geometry",
    video_url: null,
    sort: 9,
    active: true,
  },
  {
    id: "hero-11",
    subject_slug: "mathematics",
    title: "Rates of change",
    subtitle: "Calculus in motion",
    body: "Derivatives, integrals and the mathematics of becoming.",
    image_key: "math-calculus",
    image_url: null,
    link_to: "/mathematics/calculus",
    video_url: null,
    sort: 10,
    active: true,
  },
  {
    id: "hero-12",
    subject_slug: "mathematics",
    title: "Signal in the noise",
    subtitle: "Statistics that think",
    body: "Data, chance and the discipline of not being fooled.",
    image_key: "math-statistics",
    image_url: null,
    link_to: "/mathematics/statistics",
    video_url: null,
    sort: 11,
    active: true,
  },
  {
    id: "hero-13",
    subject_slug: "science",
    title: "Laws of motion",
    subtitle: "Physics of matter and light",
    body: "Force, energy and the hidden order of the world.",
    image_key: "sci-physics",
    image_url: null,
    link_to: "/science/physics",
    video_url: null,
    sort: 12,
    active: true,
  },
  {
    id: "hero-14",
    subject_slug: "science",
    title: "The flask and the flame",
    subtitle: "Chemistry of transformation",
    body: "Atoms bond, break and become something new.",
    image_key: "sci-chemistry",
    image_url: null,
    link_to: "/science/chemistry",
    video_url: null,
    sort: 13,
    active: true,
  },
  {
    id: "hero-15",
    subject_slug: "science",
    title: "A living planet",
    subtitle: "Earth from the terminator",
    body: "Rock, water, atmosphere and the thin green film of life.",
    image_key: "sci-earth",
    image_url: null,
    link_to: "/science/earth-science",
    video_url: null,
    sort: 14,
    active: true,
  },
  {
    id: "hero-16",
    subject_slug: "science",
    title: "How we know",
    subtitle: "The scientific method",
    body: "Observe, hypothesise, test, revise — a craft as much as a creed.",
    image_key: "sci-method",
    image_url: null,
    link_to: "/science/scientific-method",
    video_url: null,
    sort: 15,
    active: true,
  },
  {
    id: "hero-17",
    subject_slug: "english",
    title: "Stories that think",
    subtitle: "Literature close-up",
    body: "Plot, voice and the architecture of meaning.",
    image_key: "eng-literature",
    image_url: null,
    link_to: "/english/literature",
    video_url: null,
    sort: 16,
    active: true,
  },
  {
    id: "hero-18",
    subject_slug: "english",
    title: "Compressed fire",
    subtitle: "Poetry and image",
    body: "Meter, metaphor and the shortest path to feeling.",
    image_key: "eng-poetry",
    image_url: null,
    link_to: "/english/poetry",
    video_url: null,
    sort: 17,
    active: true,
  },
  {
    id: "hero-19",
    subject_slug: "english",
    title: "The grammar of thought",
    subtitle: "How sentences work",
    body: "Parts of speech, syntax and the machinery of clarity.",
    image_key: "eng-grammar",
    image_url: null,
    link_to: "/english/grammar",
    video_url: null,
    sort: 18,
    active: true,
  },
  {
    id: "hero-20",
    subject_slug: "english",
    title: "Ink and argument",
    subtitle: "The craft of writing",
    body: "Draft, revise, cut — until the page says only what it must.",
    image_key: "eng-writing",
    image_url: null,
    link_to: "/english/writing",
    video_url: null,
    sort: 19,
    active: true,
  },
  {
    id: "hero-21",
    subject_slug: "history",
    title: "First cities",
    subtitle: "The ancient world",
    body: "Rivers, writing and the birth of states.",
    image_key: "his-ancient",
    image_url: null,
    link_to: "/history/ancient-world",
    video_url: null,
    sort: 20,
    active: true,
  },
  {
    id: "hero-22",
    subject_slug: "history",
    title: "Castles and codes",
    subtitle: "The medieval centuries",
    body: "Faith, feudal bonds and the slow making of Europe.",
    image_key: "his-medieval",
    image_url: null,
    link_to: "/history/medieval-world",
    video_url: null,
    sort: 21,
    active: true,
  },
  {
    id: "hero-23",
    subject_slug: "history",
    title: "The world remade",
    subtitle: "Revolutions",
    body: "When ideas and crowds overturn a political order.",
    image_key: "his-revolutions",
    image_url: null,
    link_to: "/history/revolutions",
    video_url: null,
    sort: 22,
    active: true,
  },
  {
    id: "hero-24",
    subject_slug: "history",
    title: "Conflict and consequence",
    subtitle: "Wars that changed maps",
    body: "Causes, campaigns and the long shadow after the guns stop.",
    image_key: "his-wars",
    image_url: null,
    link_to: "/history/wars",
    video_url: null,
    sort: 23,
    active: true,
  },
  {
    id: "hero-25",
    subject_slug: "technology",
    title: "Machines that think in steps",
    subtitle: "Computing",
    body: "Algorithms, hardware and the flow of information.",
    image_key: "tech-computing",
    image_url: null,
    link_to: "/technology/computing",
    video_url: null,
    sort: 24,
    active: true,
  },
  {
    id: "hero-26",
    subject_slug: "technology",
    title: "Write the machine",
    subtitle: "Programming as craft",
    body: "Languages, types and the discipline of making software that lasts.",
    image_key: "tech-programming",
    image_url: null,
    link_to: "/technology/programming",
    video_url: null,
    sort: 25,
    active: true,
  },
];
