/** Artwork key for each section slug. */
export const SECTION_IMAGE_KEY: Record<string, string> = {
  organisms: "cat-organisms",
  "cells-microscopy": "hero-cell",
  "genetics-dna": "cat-genetics",
  "human-biology": "cat-human",
  plants: "cat-plants",
  "ecology-environment": "cat-ecology",
  evolution: "cat-evolution",
  "biological-processes": "discovery-leaf",
  anatomy: "cat-human",
  biotechnology: "cat-genetics",
  algebra: "math-algebra",
  geometry: "math-geometry",
  calculus: "math-calculus",
  statistics: "math-statistics",
  physics: "sci-physics",
  chemistry: "sci-chemistry",
  "earth-science": "sci-earth",
  "scientific-method": "sci-method",
  literature: "eng-literature",
  poetry: "eng-poetry",
  grammar: "eng-grammar",
  writing: "eng-writing",
  "ancient-world": "his-ancient",
  "medieval-world": "his-medieval",
  revolutions: "his-revolutions",
  wars: "his-wars",
  computing: "tech-computing",
  programming: "tech-programming",
  "artificial-intelligence": "tech-ai",
  cybersecurity: "tech-security",
};
