/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectRouteImport } from './routes/$subject'
import { Route as AddAppRouteImport } from './routes/add-app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AnatomyRouteImport } from './routes/anatomy'
import { Route as AnnotationSysRouteImport } from './routes/annotation-sys'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ArticlesDebugRouteImport } from './routes/articles-debug'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BiologicalProcessesRouteImport } from './routes/biological-processes'
import { Route as BiotechnologyRouteImport } from './routes/biotechnology'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CellsMicroscopyRouteImport } from './routes/cells-microscopy'
import { Route as ChronosOsRouteImport } from './routes/chronos-os'
import { Route as CommunicationalSystemRouteImport } from './routes/communicational-system'
import { Route as CustomListsRouteImport } from './routes/custom-lists'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DecipherRouteImport } from './routes/decipher'
import { Route as DevDashboardRouteImport } from './routes/dev-dashboard'
import { Route as DevToolsRouteImport } from './routes/dev-tools'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DownloadableSoftwareRouteImport } from './routes/downloadable-software'
import { Route as EcologyEnvironmentRouteImport } from './routes/ecology-environment'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as ExtensionToolsUploadRouteImport } from './routes/extension-tools-upload'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as GeneticsDnaRouteImport } from './routes/genetics-dna'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as GraphicationRouteImport } from './routes/graphication'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as HumanBiologyRouteImport } from './routes/human-biology'
import { Route as IdeSystemRouteImport } from './routes/ide-system'
import { Route as InformationUseRouteImport } from './routes/information-use'
import { Route as KnowledgeAtlasRouteImport } from './routes/knowledge-atlas'
import { Route as LlmRouteImport } from './routes/llm'
import { Route as LostAtlasRouteImport } from './routes/lost-atlas'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as OrganismsRouteImport } from './routes/organisms'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as PhotosyntheseRouteImport } from './routes/photosynthese'
import { Route as PhotosynthesisRouteImport } from './routes/photosynthesis'
import { Route as PlantsRouteImport } from './routes/plants'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SoftOsAdditionRouteImport } from './routes/soft-os-addition'
import { Route as SpeciesScanRouteImport } from './routes/species-scan'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as UpdateSoftRouteImport } from './routes/update-soft'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SectionTopicRouteImport } from './routes/$section.$topic'
import { Route as SubjectSectionRouteImport } from './routes/$subject.$section'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPagesListRouteImport } from './routes/admin.pages-list'
import { Route as AdminSectionsRouteImport } from './routes/admin.sections'
import { Route as AdminTopicsRouteImport } from './routes/admin.topics'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ArticlesCellularRespirationRouteImport } from './routes/articles.cellular-respiration'
import { Route as ArticlesEnzymeCatalysisRouteImport } from './routes/articles.enzyme-catalysis'
import { Route as ArticlesEvolutionNaturalSelectionRouteImport } from './routes/articles.evolution-natural-selection'
import { Route as ArticlesFoodChainsEnergyFlowRouteImport } from './routes/articles.food-chains-energy-flow'
import { Route as ArticlesHumanAnatomySystemsRouteImport } from './routes/articles.human-anatomy-systems'
import { Route as ArticlesMeiosisGameteFormationRouteImport } from './routes/articles.meiosis-gamete-formation'
import { Route as ArticlesMitosisCellDivisionRouteImport } from './routes/articles.mitosis-cell-division'
import { Route as ArticlesPhotosynthesisLightReactionsRouteImport } from './routes/articles.photosynthesis-light-reactions'
import { Route as ExtensionsNoterRouteImport } from './routes/extensions.noter'
import { Route as LostAtlasSlugRouteImport } from './routes/lost-atlas.$slug'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as TutorialsSlugRouteImport } from './routes/tutorials.$slug'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as SubjectSectionTopicRouteImport } from './routes/$subject.$section.$topic'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectRoute = SubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const AddAppRoute = AddAppRouteImport.update({
  id: '/add-app',
  path: '/add-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomyRoute = AnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationSysRoute = AnnotationSysRouteImport.update({
  id: '/annotation-sys',
  path: '/annotation-sys',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesDebugRoute = ArticlesDebugRouteImport.update({
  id: '/articles-debug',
  path: '/articles-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BiologicalProcessesRoute = BiologicalProcessesRouteImport.update({
  id: '/biological-processes',
  path: '/biological-processes',
  getParentRoute: () => rootRouteImport,
} as any)
const BiotechnologyRoute = BiotechnologyRouteImport.update({
  id: '/biotechnology',
  path: '/biotechnology',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsMicroscopyRoute = CellsMicroscopyRouteImport.update({
  id: '/cells-microscopy',
  path: '/cells-microscopy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronosOsRoute = ChronosOsRouteImport.update({
  id: '/chronos-os',
  path: '/chronos-os',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationalSystemRoute = CommunicationalSystemRouteImport.update({
  id: '/communicational-system',
  path: '/communicational-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomListsRoute = CustomListsRouteImport.update({
  id: '/custom-lists',
  path: '/custom-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DecipherRoute = DecipherRouteImport.update({
  id: '/decipher',
  path: '/decipher',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDashboardRoute = DevDashboardRouteImport.update({
  id: '/dev-dashboard',
  path: '/dev-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsRoute = DevToolsRouteImport.update({
  id: '/dev-tools',
  path: '/dev-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadableSoftwareRoute = DownloadableSoftwareRouteImport.update({
  id: '/downloadable-software',
  path: '/downloadable-software',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyEnvironmentRoute = EcologyEnvironmentRouteImport.update({
  id: '/ecology-environment',
  path: '/ecology-environment',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionToolsUploadRoute = ExtensionToolsUploadRouteImport.update({
  id: '/extension-tools-upload',
  path: '/extension-tools-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneticsDnaRoute = GeneticsDnaRouteImport.update({
  id: '/genetics-dna',
  path: '/genetics-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicationRoute = GraphicationRouteImport.update({
  id: '/graphication',
  path: '/graphication',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanBiologyRoute = HumanBiologyRouteImport.update({
  id: '/human-biology',
  path: '/human-biology',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeSystemRoute = IdeSystemRouteImport.update({
  id: '/ide-system',
  path: '/ide-system',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationUseRoute = InformationUseRouteImport.update({
  id: '/information-use',
  path: '/information-use',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeAtlasRoute = KnowledgeAtlasRouteImport.update({
  id: '/knowledge-atlas',
  path: '/knowledge-atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmRoute = LlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const LostAtlasRoute = LostAtlasRouteImport.update({
  id: '/lost-atlas',
  path: '/lost-atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganismsRoute = OrganismsRouteImport.update({
  id: '/organisms',
  path: '/organisms',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosyntheseRoute = PhotosyntheseRouteImport.update({
  id: '/photosynthese',
  path: '/photosynthese',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosynthesisRoute = PhotosynthesisRouteImport.update({
  id: '/photosynthesis',
  path: '/photosynthesis',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsRoute = PlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftOsAdditionRoute = SoftOsAdditionRouteImport.update({
  id: '/soft-os-addition',
  path: '/soft-os-addition',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesScanRoute = SpeciesScanRouteImport.update({
  id: '/species-scan',
  path: '/species-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateSoftRoute = UpdateSoftRouteImport.update({
  id: '/update-soft',
  path: '/update-soft',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionTopicRoute = SectionTopicRouteImport.update({
  id: '/$section/$topic',
  path: '/$section/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSectionRoute = SubjectSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SubjectRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesListRoute = AdminPagesListRouteImport.update({
  id: '/pages-list',
  path: '/pages-list',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopicsRoute = AdminTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AdminRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesCellularRespirationRoute =
  ArticlesCellularRespirationRouteImport.update({
    id: '/cellular-respiration',
    path: '/cellular-respiration',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesEnzymeCatalysisRoute = ArticlesEnzymeCatalysisRouteImport.update({
  id: '/enzyme-catalysis',
  path: '/enzyme-catalysis',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesEvolutionNaturalSelectionRoute =
  ArticlesEvolutionNaturalSelectionRouteImport.update({
    id: '/evolution-natural-selection',
    path: '/evolution-natural-selection',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesFoodChainsEnergyFlowRoute =
  ArticlesFoodChainsEnergyFlowRouteImport.update({
    id: '/food-chains-energy-flow',
    path: '/food-chains-energy-flow',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesHumanAnatomySystemsRoute =
  ArticlesHumanAnatomySystemsRouteImport.update({
    id: '/human-anatomy-systems',
    path: '/human-anatomy-systems',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesMeiosisGameteFormationRoute =
  ArticlesMeiosisGameteFormationRouteImport.update({
    id: '/meiosis-gamete-formation',
    path: '/meiosis-gamete-formation',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesMitosisCellDivisionRoute =
  ArticlesMitosisCellDivisionRouteImport.update({
    id: '/mitosis-cell-division',
    path: '/mitosis-cell-division',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPhotosynthesisLightReactionsRoute =
  ArticlesPhotosynthesisLightReactionsRouteImport.update({
    id: '/photosynthesis-light-reactions',
    path: '/photosynthesis-light-reactions',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ExtensionsNoterRoute = ExtensionsNoterRouteImport.update({
  id: '/noter',
  path: '/noter',
  getParentRoute: () => ExtensionsRoute,
} as any)
const LostAtlasSlugRoute = LostAtlasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LostAtlasRoute,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const TutorialsSlugRoute = TutorialsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TutorialsRoute,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VideosRoute,
} as any)
const SubjectSectionTopicRoute = SubjectSectionTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => SubjectSectionRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/add-app': typeof AddAppRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/anatomy': typeof AnatomyRoute
  '/annotation-sys': typeof AnnotationSysRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/articles-debug': typeof ArticlesDebugRoute
  '/auth': typeof AuthRoute
  '/biological-processes': typeof BiologicalProcessesRoute
  '/biotechnology': typeof BiotechnologyRoute
  '/categories': typeof CategoriesRoute
  '/cells-microscopy': typeof CellsMicroscopyRoute
  '/chronos-os': typeof ChronosOsRoute
  '/communicational-system': typeof CommunicationalSystemRoute
  '/custom-lists': typeof CustomListsRoute
  '/dashboard': typeof DashboardRoute
  '/decipher': typeof DecipherRoute
  '/dev-dashboard': typeof DevDashboardRoute
  '/dev-tools': typeof DevToolsRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/downloadable-software': typeof DownloadableSoftwareRoute
  '/ecology-environment': typeof EcologyEnvironmentRoute
  '/evolution': typeof EvolutionRoute
  '/extension-tools-upload': typeof ExtensionToolsUploadRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/flashcards': typeof FlashcardsRoute
  '/genetics-dna': typeof GeneticsDnaRoute
  '/glossary': typeof GlossaryRoute
  '/graphication': typeof GraphicationRoute
  '/help-center': typeof HelpCenterRoute
  '/human-biology': typeof HumanBiologyRoute
  '/ide-system': typeof IdeSystemRoute
  '/information-use': typeof InformationUseRoute
  '/knowledge-atlas': typeof KnowledgeAtlasRoute
  '/llm': typeof LlmRoute
  '/lost-atlas': typeof LostAtlasRouteWithChildren
  '/maps': typeof MapsRoute
  '/network': typeof NetworkRoute
  '/notebook': typeof NotebookRoute
  '/organisms': typeof OrganismsRoute
  '/pages': typeof PagesRouteWithChildren
  '/photosynthese': typeof PhotosyntheseRoute
  '/photosynthesis': typeof PhotosynthesisRoute
  '/plants': typeof PlantsRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/soft-os-addition': typeof SoftOsAdditionRoute
  '/species-scan': typeof SpeciesScanRoute
  '/timeline': typeof TimelineRoute
  '/translate': typeof TranslateRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/update-soft': typeof UpdateSoftRoute
  '/videos': typeof VideosRouteWithChildren
  '/$section/$topic': typeof SectionTopicRoute
  '/$subject/$section': typeof SubjectSectionRouteWithChildren
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pages-list': typeof AdminPagesListRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/cellular-respiration': typeof ArticlesCellularRespirationRoute
  '/articles/enzyme-catalysis': typeof ArticlesEnzymeCatalysisRoute
  '/articles/evolution-natural-selection': typeof ArticlesEvolutionNaturalSelectionRoute
  '/articles/food-chains-energy-flow': typeof ArticlesFoodChainsEnergyFlowRoute
  '/articles/human-anatomy-systems': typeof ArticlesHumanAnatomySystemsRoute
  '/articles/meiosis-gamete-formation': typeof ArticlesMeiosisGameteFormationRoute
  '/articles/mitosis-cell-division': typeof ArticlesMitosisCellDivisionRoute
  '/articles/photosynthesis-light-reactions': typeof ArticlesPhotosynthesisLightReactionsRoute
  '/extensions/noter': typeof ExtensionsNoterRoute
  '/lost-atlas/$slug': typeof LostAtlasSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/$subject/$section/$topic': typeof SubjectSectionTopicRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/add-app': typeof AddAppRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/anatomy': typeof AnatomyRoute
  '/annotation-sys': typeof AnnotationSysRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/articles-debug': typeof ArticlesDebugRoute
  '/auth': typeof AuthRoute
  '/biological-processes': typeof BiologicalProcessesRoute
  '/biotechnology': typeof BiotechnologyRoute
  '/categories': typeof CategoriesRoute
  '/cells-microscopy': typeof CellsMicroscopyRoute
  '/chronos-os': typeof ChronosOsRoute
  '/communicational-system': typeof CommunicationalSystemRoute
  '/custom-lists': typeof CustomListsRoute
  '/dashboard': typeof DashboardRoute
  '/decipher': typeof DecipherRoute
  '/dev-dashboard': typeof DevDashboardRoute
  '/dev-tools': typeof DevToolsRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/downloadable-software': typeof DownloadableSoftwareRoute
  '/ecology-environment': typeof EcologyEnvironmentRoute
  '/evolution': typeof EvolutionRoute
  '/extension-tools-upload': typeof ExtensionToolsUploadRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/flashcards': typeof FlashcardsRoute
  '/genetics-dna': typeof GeneticsDnaRoute
  '/glossary': typeof GlossaryRoute
  '/graphication': typeof GraphicationRoute
  '/help-center': typeof HelpCenterRoute
  '/human-biology': typeof HumanBiologyRoute
  '/ide-system': typeof IdeSystemRoute
  '/information-use': typeof InformationUseRoute
  '/knowledge-atlas': typeof KnowledgeAtlasRoute
  '/llm': typeof LlmRoute
  '/lost-atlas': typeof LostAtlasRouteWithChildren
  '/maps': typeof MapsRoute
  '/network': typeof NetworkRoute
  '/notebook': typeof NotebookRoute
  '/organisms': typeof OrganismsRoute
  '/pages': typeof PagesRouteWithChildren
  '/photosynthese': typeof PhotosyntheseRoute
  '/photosynthesis': typeof PhotosynthesisRoute
  '/plants': typeof PlantsRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/soft-os-addition': typeof SoftOsAdditionRoute
  '/species-scan': typeof SpeciesScanRoute
  '/timeline': typeof TimelineRoute
  '/translate': typeof TranslateRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/update-soft': typeof UpdateSoftRoute
  '/videos': typeof VideosRouteWithChildren
  '/$section/$topic': typeof SectionTopicRoute
  '/$subject/$section': typeof SubjectSectionRouteWithChildren
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pages-list': typeof AdminPagesListRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/cellular-respiration': typeof ArticlesCellularRespirationRoute
  '/articles/enzyme-catalysis': typeof ArticlesEnzymeCatalysisRoute
  '/articles/evolution-natural-selection': typeof ArticlesEvolutionNaturalSelectionRoute
  '/articles/food-chains-energy-flow': typeof ArticlesFoodChainsEnergyFlowRoute
  '/articles/human-anatomy-systems': typeof ArticlesHumanAnatomySystemsRoute
  '/articles/meiosis-gamete-formation': typeof ArticlesMeiosisGameteFormationRoute
  '/articles/mitosis-cell-division': typeof ArticlesMitosisCellDivisionRoute
  '/articles/photosynthesis-light-reactions': typeof ArticlesPhotosynthesisLightReactionsRoute
  '/extensions/noter': typeof ExtensionsNoterRoute
  '/lost-atlas/$slug': typeof LostAtlasSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/$subject/$section/$topic': typeof SubjectSectionTopicRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/add-app': typeof AddAppRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/anatomy': typeof AnatomyRoute
  '/annotation-sys': typeof AnnotationSysRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/articles-debug': typeof ArticlesDebugRoute
  '/auth': typeof AuthRoute
  '/biological-processes': typeof BiologicalProcessesRoute
  '/biotechnology': typeof BiotechnologyRoute
  '/categories': typeof CategoriesRoute
  '/cells-microscopy': typeof CellsMicroscopyRoute
  '/chronos-os': typeof ChronosOsRoute
  '/communicational-system': typeof CommunicationalSystemRoute
  '/custom-lists': typeof CustomListsRoute
  '/dashboard': typeof DashboardRoute
  '/decipher': typeof DecipherRoute
  '/dev-dashboard': typeof DevDashboardRoute
  '/dev-tools': typeof DevToolsRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/downloadable-software': typeof DownloadableSoftwareRoute
  '/ecology-environment': typeof EcologyEnvironmentRoute
  '/evolution': typeof EvolutionRoute
  '/extension-tools-upload': typeof ExtensionToolsUploadRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/flashcards': typeof FlashcardsRoute
  '/genetics-dna': typeof GeneticsDnaRoute
  '/glossary': typeof GlossaryRoute
  '/graphication': typeof GraphicationRoute
  '/help-center': typeof HelpCenterRoute
  '/human-biology': typeof HumanBiologyRoute
  '/ide-system': typeof IdeSystemRoute
  '/information-use': typeof InformationUseRoute
  '/knowledge-atlas': typeof KnowledgeAtlasRoute
  '/llm': typeof LlmRoute
  '/lost-atlas': typeof LostAtlasRouteWithChildren
  '/maps': typeof MapsRoute
  '/network': typeof NetworkRoute
  '/notebook': typeof NotebookRoute
  '/organisms': typeof OrganismsRoute
  '/pages': typeof PagesRouteWithChildren
  '/photosynthese': typeof PhotosyntheseRoute
  '/photosynthesis': typeof PhotosynthesisRoute
  '/plants': typeof PlantsRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/soft-os-addition': typeof SoftOsAdditionRoute
  '/species-scan': typeof SpeciesScanRoute
  '/timeline': typeof TimelineRoute
  '/translate': typeof TranslateRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/update-soft': typeof UpdateSoftRoute
  '/videos': typeof VideosRouteWithChildren
  '/$section/$topic': typeof SectionTopicRoute
  '/$subject/$section': typeof SubjectSectionRouteWithChildren
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pages-list': typeof AdminPagesListRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/cellular-respiration': typeof ArticlesCellularRespirationRoute
  '/articles/enzyme-catalysis': typeof ArticlesEnzymeCatalysisRoute
  '/articles/evolution-natural-selection': typeof ArticlesEvolutionNaturalSelectionRoute
  '/articles/food-chains-energy-flow': typeof ArticlesFoodChainsEnergyFlowRoute
  '/articles/human-anatomy-systems': typeof ArticlesHumanAnatomySystemsRoute
  '/articles/meiosis-gamete-formation': typeof ArticlesMeiosisGameteFormationRoute
  '/articles/mitosis-cell-division': typeof ArticlesMitosisCellDivisionRoute
  '/articles/photosynthesis-light-reactions': typeof ArticlesPhotosynthesisLightReactionsRoute
  '/extensions/noter': typeof ExtensionsNoterRoute
  '/lost-atlas/$slug': typeof LostAtlasSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/$subject/$section/$topic': typeof SubjectSectionTopicRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$subject'
    | '/add-app'
    | '/admin'
    | '/ai'
    | '/anatomy'
    | '/annotation-sys'
    | '/articles'
    | '/articles-debug'
    | '/auth'
    | '/biological-processes'
    | '/biotechnology'
    | '/categories'
    | '/cells-microscopy'
    | '/chronos-os'
    | '/communicational-system'
    | '/custom-lists'
    | '/dashboard'
    | '/decipher'
    | '/dev-dashboard'
    | '/dev-tools'
    | '/docs'
    | '/download'
    | '/downloadable-software'
    | '/ecology-environment'
    | '/evolution'
    | '/extension-tools-upload'
    | '/extensions'
    | '/flashcards'
    | '/genetics-dna'
    | '/glossary'
    | '/graphication'
    | '/help-center'
    | '/human-biology'
    | '/ide-system'
    | '/information-use'
    | '/knowledge-atlas'
    | '/llm'
    | '/lost-atlas'
    | '/maps'
    | '/network'
    | '/notebook'
    | '/organisms'
    | '/pages'
    | '/photosynthese'
    | '/photosynthesis'
    | '/plants'
    | '/privacy'
    | '/quizzes'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/soft-os-addition'
    | '/species-scan'
    | '/timeline'
    | '/translate'
    | '/tutorials'
    | '/update-soft'
    | '/videos'
    | '/$section/$topic'
    | '/$subject/$section'
    | '/admin/articles'
    | '/admin/pages'
    | '/admin/pages-list'
    | '/admin/sections'
    | '/admin/topics'
    | '/articles/$slug'
    | '/articles/cellular-respiration'
    | '/articles/enzyme-catalysis'
    | '/articles/evolution-natural-selection'
    | '/articles/food-chains-energy-flow'
    | '/articles/human-anatomy-systems'
    | '/articles/meiosis-gamete-formation'
    | '/articles/mitosis-cell-division'
    | '/articles/photosynthesis-light-reactions'
    | '/extensions/noter'
    | '/lost-atlas/$slug'
    | '/pages/$slug'
    | '/tutorials/$slug'
    | '/videos/$slug'
    | '/$subject/$section/$topic'
    | '/admin/articles/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$subject'
    | '/add-app'
    | '/admin'
    | '/ai'
    | '/anatomy'
    | '/annotation-sys'
    | '/articles'
    | '/articles-debug'
    | '/auth'
    | '/biological-processes'
    | '/biotechnology'
    | '/categories'
    | '/cells-microscopy'
    | '/chronos-os'
    | '/communicational-system'
    | '/custom-lists'
    | '/dashboard'
    | '/decipher'
    | '/dev-dashboard'
    | '/dev-tools'
    | '/docs'
    | '/download'
    | '/downloadable-software'
    | '/ecology-environment'
    | '/evolution'
    | '/extension-tools-upload'
    | '/extensions'
    | '/flashcards'
    | '/genetics-dna'
    | '/glossary'
    | '/graphication'
    | '/help-center'
    | '/human-biology'
    | '/ide-system'
    | '/information-use'
    | '/knowledge-atlas'
    | '/llm'
    | '/lost-atlas'
    | '/maps'
    | '/network'
    | '/notebook'
    | '/organisms'
    | '/pages'
    | '/photosynthese'
    | '/photosynthesis'
    | '/plants'
    | '/privacy'
    | '/quizzes'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/soft-os-addition'
    | '/species-scan'
    | '/timeline'
    | '/translate'
    | '/tutorials'
    | '/update-soft'
    | '/videos'
    | '/$section/$topic'
    | '/$subject/$section'
    | '/admin/articles'
    | '/admin/pages'
    | '/admin/pages-list'
    | '/admin/sections'
    | '/admin/topics'
    | '/articles/$slug'
    | '/articles/cellular-respiration'
    | '/articles/enzyme-catalysis'
    | '/articles/evolution-natural-selection'
    | '/articles/food-chains-energy-flow'
    | '/articles/human-anatomy-systems'
    | '/articles/meiosis-gamete-formation'
    | '/articles/mitosis-cell-division'
    | '/articles/photosynthesis-light-reactions'
    | '/extensions/noter'
    | '/lost-atlas/$slug'
    | '/pages/$slug'
    | '/tutorials/$slug'
    | '/videos/$slug'
    | '/$subject/$section/$topic'
    | '/admin/articles/new'
  id:
    | '__root__'
    | '/'
    | '/$subject'
    | '/add-app'
    | '/admin'
    | '/ai'
    | '/anatomy'
    | '/annotation-sys'
    | '/articles'
    | '/articles-debug'
    | '/auth'
    | '/biological-processes'
    | '/biotechnology'
    | '/categories'
    | '/cells-microscopy'
    | '/chronos-os'
    | '/communicational-system'
    | '/custom-lists'
    | '/dashboard'
    | '/decipher'
    | '/dev-dashboard'
    | '/dev-tools'
    | '/docs'
    | '/download'
    | '/downloadable-software'
    | '/ecology-environment'
    | '/evolution'
    | '/extension-tools-upload'
    | '/extensions'
    | '/flashcards'
    | '/genetics-dna'
    | '/glossary'
    | '/graphication'
    | '/help-center'
    | '/human-biology'
    | '/ide-system'
    | '/information-use'
    | '/knowledge-atlas'
    | '/llm'
    | '/lost-atlas'
    | '/maps'
    | '/network'
    | '/notebook'
    | '/organisms'
    | '/pages'
    | '/photosynthese'
    | '/photosynthesis'
    | '/plants'
    | '/privacy'
    | '/quizzes'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/soft-os-addition'
    | '/species-scan'
    | '/timeline'
    | '/translate'
    | '/tutorials'
    | '/update-soft'
    | '/videos'
    | '/$section/$topic'
    | '/$subject/$section'
    | '/admin/articles'
    | '/admin/pages'
    | '/admin/pages-list'
    | '/admin/sections'
    | '/admin/topics'
    | '/articles/$slug'
    | '/articles/cellular-respiration'
    | '/articles/enzyme-catalysis'
    | '/articles/evolution-natural-selection'
    | '/articles/food-chains-energy-flow'
    | '/articles/human-anatomy-systems'
    | '/articles/meiosis-gamete-formation'
    | '/articles/mitosis-cell-division'
    | '/articles/photosynthesis-light-reactions'
    | '/extensions/noter'
    | '/lost-atlas/$slug'
    | '/pages/$slug'
    | '/tutorials/$slug'
    | '/videos/$slug'
    | '/$subject/$section/$topic'
    | '/admin/articles/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjectRoute: typeof SubjectRouteWithChildren
  AddAppRoute: typeof AddAppRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  AnatomyRoute: typeof AnatomyRoute
  AnnotationSysRoute: typeof AnnotationSysRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ArticlesDebugRoute: typeof ArticlesDebugRoute
  AuthRoute: typeof AuthRoute
  BiologicalProcessesRoute: typeof BiologicalProcessesRoute
  BiotechnologyRoute: typeof BiotechnologyRoute
  CategoriesRoute: typeof CategoriesRoute
  CellsMicroscopyRoute: typeof CellsMicroscopyRoute
  ChronosOsRoute: typeof ChronosOsRoute
  CommunicationalSystemRoute: typeof CommunicationalSystemRoute
  CustomListsRoute: typeof CustomListsRoute
  DashboardRoute: typeof DashboardRoute
  DecipherRoute: typeof DecipherRoute
  DevDashboardRoute: typeof DevDashboardRoute
  DevToolsRoute: typeof DevToolsRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  DownloadableSoftwareRoute: typeof DownloadableSoftwareRoute
  EcologyEnvironmentRoute: typeof EcologyEnvironmentRoute
  EvolutionRoute: typeof EvolutionRoute
  ExtensionToolsUploadRoute: typeof ExtensionToolsUploadRoute
  ExtensionsRoute: typeof ExtensionsRouteWithChildren
  FlashcardsRoute: typeof FlashcardsRoute
  GeneticsDnaRoute: typeof GeneticsDnaRoute
  GlossaryRoute: typeof GlossaryRoute
  GraphicationRoute: typeof GraphicationRoute
  HelpCenterRoute: typeof HelpCenterRoute
  HumanBiologyRoute: typeof HumanBiologyRoute
  IdeSystemRoute: typeof IdeSystemRoute
  InformationUseRoute: typeof InformationUseRoute
  KnowledgeAtlasRoute: typeof KnowledgeAtlasRoute
  LlmRoute: typeof LlmRoute
  LostAtlasRoute: typeof LostAtlasRouteWithChildren
  MapsRoute: typeof MapsRoute
  NetworkRoute: typeof NetworkRoute
  NotebookRoute: typeof NotebookRoute
  OrganismsRoute: typeof OrganismsRoute
  PagesRoute: typeof PagesRouteWithChildren
  PhotosyntheseRoute: typeof PhotosyntheseRoute
  PhotosynthesisRoute: typeof PhotosynthesisRoute
  PlantsRoute: typeof PlantsRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizzesRoute: typeof QuizzesRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SoftOsAdditionRoute: typeof SoftOsAdditionRoute
  SpeciesScanRoute: typeof SpeciesScanRoute
  TimelineRoute: typeof TimelineRoute
  TranslateRoute: typeof TranslateRoute
  TutorialsRoute: typeof TutorialsRouteWithChildren
  UpdateSoftRoute: typeof UpdateSoftRoute
  VideosRoute: typeof VideosRouteWithChildren
  SectionTopicRoute: typeof SectionTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject': {
      id: '/$subject'
      path: '/$subject'
      fullPath: '/$subject'
      preLoaderRoute: typeof SubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-app': {
      id: '/add-app'
      path: '/add-app'
      fullPath: '/add-app'
      preLoaderRoute: typeof AddAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomy': {
      id: '/anatomy'
      path: '/anatomy'
      fullPath: '/anatomy'
      preLoaderRoute: typeof AnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotation-sys': {
      id: '/annotation-sys'
      path: '/annotation-sys'
      fullPath: '/annotation-sys'
      preLoaderRoute: typeof AnnotationSysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles-debug': {
      id: '/articles-debug'
      path: '/articles-debug'
      fullPath: '/articles-debug'
      preLoaderRoute: typeof ArticlesDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biological-processes': {
      id: '/biological-processes'
      path: '/biological-processes'
      fullPath: '/biological-processes'
      preLoaderRoute: typeof BiologicalProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biotechnology': {
      id: '/biotechnology'
      path: '/biotechnology'
      fullPath: '/biotechnology'
      preLoaderRoute: typeof BiotechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cells-microscopy': {
      id: '/cells-microscopy'
      path: '/cells-microscopy'
      fullPath: '/cells-microscopy'
      preLoaderRoute: typeof CellsMicroscopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronos-os': {
      id: '/chronos-os'
      path: '/chronos-os'
      fullPath: '/chronos-os'
      preLoaderRoute: typeof ChronosOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communicational-system': {
      id: '/communicational-system'
      path: '/communicational-system'
      fullPath: '/communicational-system'
      preLoaderRoute: typeof CommunicationalSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-lists': {
      id: '/custom-lists'
      path: '/custom-lists'
      fullPath: '/custom-lists'
      preLoaderRoute: typeof CustomListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decipher': {
      id: '/decipher'
      path: '/decipher'
      fullPath: '/decipher'
      preLoaderRoute: typeof DecipherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-dashboard': {
      id: '/dev-dashboard'
      path: '/dev-dashboard'
      fullPath: '/dev-dashboard'
      preLoaderRoute: typeof DevDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools': {
      id: '/dev-tools'
      path: '/dev-tools'
      fullPath: '/dev-tools'
      preLoaderRoute: typeof DevToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloadable-software': {
      id: '/downloadable-software'
      path: '/downloadable-software'
      fullPath: '/downloadable-software'
      preLoaderRoute: typeof DownloadableSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology-environment': {
      id: '/ecology-environment'
      path: '/ecology-environment'
      fullPath: '/ecology-environment'
      preLoaderRoute: typeof EcologyEnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension-tools-upload': {
      id: '/extension-tools-upload'
      path: '/extension-tools-upload'
      fullPath: '/extension-tools-upload'
      preLoaderRoute: typeof ExtensionToolsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genetics-dna': {
      id: '/genetics-dna'
      path: '/genetics-dna'
      fullPath: '/genetics-dna'
      preLoaderRoute: typeof GeneticsDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphication': {
      id: '/graphication'
      path: '/graphication'
      fullPath: '/graphication'
      preLoaderRoute: typeof GraphicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-biology': {
      id: '/human-biology'
      path: '/human-biology'
      fullPath: '/human-biology'
      preLoaderRoute: typeof HumanBiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ide-system': {
      id: '/ide-system'
      path: '/ide-system'
      fullPath: '/ide-system'
      preLoaderRoute: typeof IdeSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information-use': {
      id: '/information-use'
      path: '/information-use'
      fullPath: '/information-use'
      preLoaderRoute: typeof InformationUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-atlas': {
      id: '/knowledge-atlas'
      path: '/knowledge-atlas'
      fullPath: '/knowledge-atlas'
      preLoaderRoute: typeof KnowledgeAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm': {
      id: '/llm'
      path: '/llm'
      fullPath: '/llm'
      preLoaderRoute: typeof LlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-atlas': {
      id: '/lost-atlas'
      path: '/lost-atlas'
      fullPath: '/lost-atlas'
      preLoaderRoute: typeof LostAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisms': {
      id: '/organisms'
      path: '/organisms'
      fullPath: '/organisms'
      preLoaderRoute: typeof OrganismsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photosynthese': {
      id: '/photosynthese'
      path: '/photosynthese'
      fullPath: '/photosynthese'
      preLoaderRoute: typeof PhotosyntheseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photosynthesis': {
      id: '/photosynthesis'
      path: '/photosynthesis'
      fullPath: '/photosynthesis'
      preLoaderRoute: typeof PhotosynthesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants': {
      id: '/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof PlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soft-os-addition': {
      id: '/soft-os-addition'
      path: '/soft-os-addition'
      fullPath: '/soft-os-addition'
      preLoaderRoute: typeof SoftOsAdditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species-scan': {
      id: '/species-scan'
      path: '/species-scan'
      fullPath: '/species-scan'
      preLoaderRoute: typeof SpeciesScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-soft': {
      id: '/update-soft'
      path: '/update-soft'
      fullPath: '/update-soft'
      preLoaderRoute: typeof UpdateSoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$topic': {
      id: '/$section/$topic'
      path: '/$section/$topic'
      fullPath: '/$section/$topic'
      preLoaderRoute: typeof SectionTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject/$section': {
      id: '/$subject/$section'
      path: '/$section'
      fullPath: '/$subject/$section'
      preLoaderRoute: typeof SubjectSectionRouteImport
      parentRoute: typeof SubjectRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages-list': {
      id: '/admin/pages-list'
      path: '/pages-list'
      fullPath: '/admin/pages-list'
      preLoaderRoute: typeof AdminPagesListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/topics': {
      id: '/admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminTopicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/cellular-respiration': {
      id: '/articles/cellular-respiration'
      path: '/cellular-respiration'
      fullPath: '/articles/cellular-respiration'
      preLoaderRoute: typeof ArticlesCellularRespirationRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/enzyme-catalysis': {
      id: '/articles/enzyme-catalysis'
      path: '/enzyme-catalysis'
      fullPath: '/articles/enzyme-catalysis'
      preLoaderRoute: typeof ArticlesEnzymeCatalysisRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/evolution-natural-selection': {
      id: '/articles/evolution-natural-selection'
      path: '/evolution-natural-selection'
      fullPath: '/articles/evolution-natural-selection'
      preLoaderRoute: typeof ArticlesEvolutionNaturalSelectionRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/food-chains-energy-flow': {
      id: '/articles/food-chains-energy-flow'
      path: '/food-chains-energy-flow'
      fullPath: '/articles/food-chains-energy-flow'
      preLoaderRoute: typeof ArticlesFoodChainsEnergyFlowRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/human-anatomy-systems': {
      id: '/articles/human-anatomy-systems'
      path: '/human-anatomy-systems'
      fullPath: '/articles/human-anatomy-systems'
      preLoaderRoute: typeof ArticlesHumanAnatomySystemsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/meiosis-gamete-formation': {
      id: '/articles/meiosis-gamete-formation'
      path: '/meiosis-gamete-formation'
      fullPath: '/articles/meiosis-gamete-formation'
      preLoaderRoute: typeof ArticlesMeiosisGameteFormationRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/mitosis-cell-division': {
      id: '/articles/mitosis-cell-division'
      path: '/mitosis-cell-division'
      fullPath: '/articles/mitosis-cell-division'
      preLoaderRoute: typeof ArticlesMitosisCellDivisionRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/photosynthesis-light-reactions': {
      id: '/articles/photosynthesis-light-reactions'
      path: '/photosynthesis-light-reactions'
      fullPath: '/articles/photosynthesis-light-reactions'
      preLoaderRoute: typeof ArticlesPhotosynthesisLightReactionsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/extensions/noter': {
      id: '/extensions/noter'
      path: '/noter'
      fullPath: '/extensions/noter'
      preLoaderRoute: typeof ExtensionsNoterRouteImport
      parentRoute: typeof ExtensionsRoute
    }
    '/lost-atlas/$slug': {
      id: '/lost-atlas/$slug'
      path: '/$slug'
      fullPath: '/lost-atlas/$slug'
      preLoaderRoute: typeof LostAtlasSlugRouteImport
      parentRoute: typeof LostAtlasRoute
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/tutorials/$slug': {
      id: '/tutorials/$slug'
      path: '/$slug'
      fullPath: '/tutorials/$slug'
      preLoaderRoute: typeof TutorialsSlugRouteImport
      parentRoute: typeof TutorialsRoute
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof VideosRoute
    }
    '/$subject/$section/$topic': {
      id: '/$subject/$section/$topic'
      path: '/$topic'
      fullPath: '/$subject/$section/$topic'
      preLoaderRoute: typeof SubjectSectionTopicRouteImport
      parentRoute: typeof SubjectSectionRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
  }
}

interface SubjectSectionRouteChildren {
  SubjectSectionTopicRoute: typeof SubjectSectionTopicRoute
}

const SubjectSectionRouteChildren: SubjectSectionRouteChildren = {
  SubjectSectionTopicRoute: SubjectSectionTopicRoute,
}

const SubjectSectionRouteWithChildren = SubjectSectionRoute._addFileChildren(
  SubjectSectionRouteChildren,
)

interface SubjectRouteChildren {
  SubjectSectionRoute: typeof SubjectSectionRouteWithChildren
}

const SubjectRouteChildren: SubjectRouteChildren = {
  SubjectSectionRoute: SubjectSectionRouteWithChildren,
}

const SubjectRouteWithChildren =
  SubjectRoute._addFileChildren(SubjectRouteChildren)

interface AdminArticlesRouteChildren {
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesNewRoute: AdminArticlesNewRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPagesListRoute: typeof AdminPagesListRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminTopicsRoute: typeof AdminTopicsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminPagesRoute: AdminPagesRoute,
  AdminPagesListRoute: AdminPagesListRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminTopicsRoute: AdminTopicsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesCellularRespirationRoute: typeof ArticlesCellularRespirationRoute
  ArticlesEnzymeCatalysisRoute: typeof ArticlesEnzymeCatalysisRoute
  ArticlesEvolutionNaturalSelectionRoute: typeof ArticlesEvolutionNaturalSelectionRoute
  ArticlesFoodChainsEnergyFlowRoute: typeof ArticlesFoodChainsEnergyFlowRoute
  ArticlesHumanAnatomySystemsRoute: typeof ArticlesHumanAnatomySystemsRoute
  ArticlesMeiosisGameteFormationRoute: typeof ArticlesMeiosisGameteFormationRoute
  ArticlesMitosisCellDivisionRoute: typeof ArticlesMitosisCellDivisionRoute
  ArticlesPhotosynthesisLightReactionsRoute: typeof ArticlesPhotosynthesisLightReactionsRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesCellularRespirationRoute: ArticlesCellularRespirationRoute,
  ArticlesEnzymeCatalysisRoute: ArticlesEnzymeCatalysisRoute,
  ArticlesEvolutionNaturalSelectionRoute:
    ArticlesEvolutionNaturalSelectionRoute,
  ArticlesFoodChainsEnergyFlowRoute: ArticlesFoodChainsEnergyFlowRoute,
  ArticlesHumanAnatomySystemsRoute: ArticlesHumanAnatomySystemsRoute,
  ArticlesMeiosisGameteFormationRoute: ArticlesMeiosisGameteFormationRoute,
  ArticlesMitosisCellDivisionRoute: ArticlesMitosisCellDivisionRoute,
  ArticlesPhotosynthesisLightReactionsRoute:
    ArticlesPhotosynthesisLightReactionsRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface ExtensionsRouteChildren {
  ExtensionsNoterRoute: typeof ExtensionsNoterRoute
}

const ExtensionsRouteChildren: ExtensionsRouteChildren = {
  ExtensionsNoterRoute: ExtensionsNoterRoute,
}

const ExtensionsRouteWithChildren = ExtensionsRoute._addFileChildren(
  ExtensionsRouteChildren,
)

interface LostAtlasRouteChildren {
  LostAtlasSlugRoute: typeof LostAtlasSlugRoute
}

const LostAtlasRouteChildren: LostAtlasRouteChildren = {
  LostAtlasSlugRoute: LostAtlasSlugRoute,
}

const LostAtlasRouteWithChildren = LostAtlasRoute._addFileChildren(
  LostAtlasRouteChildren,
)

interface PagesRouteChildren {
  PagesSlugRoute: typeof PagesSlugRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesSlugRoute: PagesSlugRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface TutorialsRouteChildren {
  TutorialsSlugRoute: typeof TutorialsSlugRoute
}

const TutorialsRouteChildren: TutorialsRouteChildren = {
  TutorialsSlugRoute: TutorialsSlugRoute,
}

const TutorialsRouteWithChildren = TutorialsRoute._addFileChildren(
  TutorialsRouteChildren,
)

interface VideosRouteChildren {
  VideosSlugRoute: typeof VideosSlugRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosSlugRoute: VideosSlugRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjectRoute: SubjectRouteWithChildren,
  AddAppRoute: AddAppRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  AnatomyRoute: AnatomyRoute,
  AnnotationSysRoute: AnnotationSysRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ArticlesDebugRoute: ArticlesDebugRoute,
  AuthRoute: AuthRoute,
  BiologicalProcessesRoute: BiologicalProcessesRoute,
  BiotechnologyRoute: BiotechnologyRoute,
  CategoriesRoute: CategoriesRoute,
  CellsMicroscopyRoute: CellsMicroscopyRoute,
  ChronosOsRoute: ChronosOsRoute,
  CommunicationalSystemRoute: CommunicationalSystemRoute,
  CustomListsRoute: CustomListsRoute,
  DashboardRoute: DashboardRoute,
  DecipherRoute: DecipherRoute,
  DevDashboardRoute: DevDashboardRoute,
  DevToolsRoute: DevToolsRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  DownloadableSoftwareRoute: DownloadableSoftwareRoute,
  EcologyEnvironmentRoute: EcologyEnvironmentRoute,
  EvolutionRoute: EvolutionRoute,
  ExtensionToolsUploadRoute: ExtensionToolsUploadRoute,
  ExtensionsRoute: ExtensionsRouteWithChildren,
  FlashcardsRoute: FlashcardsRoute,
  GeneticsDnaRoute: GeneticsDnaRoute,
  GlossaryRoute: GlossaryRoute,
  GraphicationRoute: GraphicationRoute,
  HelpCenterRoute: HelpCenterRoute,
  HumanBiologyRoute: HumanBiologyRoute,
  IdeSystemRoute: IdeSystemRoute,
  InformationUseRoute: InformationUseRoute,
  KnowledgeAtlasRoute: KnowledgeAtlasRoute,
  LlmRoute: LlmRoute,
  LostAtlasRoute: LostAtlasRouteWithChildren,
  MapsRoute: MapsRoute,
  NetworkRoute: NetworkRoute,
  NotebookRoute: NotebookRoute,
  OrganismsRoute: OrganismsRoute,
  PagesRoute: PagesRouteWithChildren,
  PhotosyntheseRoute: PhotosyntheseRoute,
  PhotosynthesisRoute: PhotosynthesisRoute,
  PlantsRoute: PlantsRoute,
  PrivacyRoute: PrivacyRoute,
  QuizzesRoute: QuizzesRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SoftOsAdditionRoute: SoftOsAdditionRoute,
  SpeciesScanRoute: SpeciesScanRoute,
  TimelineRoute: TimelineRoute,
  TranslateRoute: TranslateRoute,
  TutorialsRoute: TutorialsRouteWithChildren,
  UpdateSoftRoute: UpdateSoftRoute,
  VideosRoute: VideosRouteWithChildren,
  SectionTopicRoute: SectionTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
